# Generated by Django 5.0.2 on 2024-04-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_order_category_alter_order_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='item_image',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.itemimage'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detailcart',
        ),
    ]
