# Generated by Django 5.0.2 on 2024-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_cart_cart_user_profile_cart_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
